name: "🐞 bug report"
description: "Create a report to improve this project"
title: "[bug]: <title>"
labels:
  - "bug"
assignees:
  - "engineering"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! ~*tem. team*
  - type: checkboxes
    id: googledit
    attributes:
      label: googled it.
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: problem
    attributes:
      label: problem.
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: expected behavior.
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: reproduction steps.
      description: A guide to replicate the experienced error.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: environment.
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Release**: v1.0.0
      value: |
        - OS:
        - Release:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: logs.
      description: Please copy and paste any relevant log output.
      render: shell
  - type: textarea
    id: artifacts
    attributes:
      label: artifacts.
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
