blank_issues_enabled: false
contact_links:
  - name: "tem. Slack Community"
    url: https://tem-energy.slack.com/archives/C02UET0B268
    about: |
      tem. engineering slack channel.
      Please ask and answer questions here.
