---
name: Link pull-request to Notion
on:
  pull_request:
    types:
      - edited
      - opened
jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
      - name: Update Notion page
        uses: kadaradam/notion-pr-link@v0.1.1
        with:
          notion_secret: ${{ secrets.NOTION_TEM_WORKSPACE_SECRET }}
          notion_prop: GitHub
